# Generated by Django 5.2.7 on 2025-10-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto'),
        ),
    ]
